

CREATE TABLE BK_EMPRESAS (
ID_EMPRESA VARCHAR2(100) NOT NULL,
DESCRIPCION VARCHAR2(100) NOT NULL, 
HASH_ID VARCHAR2(200)
);

ALTER TABLE BK_EMPRESAS ADD (
  CONSTRAINT EMPRESAS_PK 
 PRIMARY KEY (ID_EMPRESA));




CREATE TABLE BK_PERSONAS (
ID_EMPRESA VARCHAR2(100) NOT NULL,
ID_PERSONA VARCHAR(200) NOT NULL,
NOMBRE VARCHAR2(100),
MAIL  VARCHAR2(100),
TIPO_DOCUMENTO  VARCHAR2(100),
NRO_DOCUMENTO VARCHAR2(100)
);


ALTER TABLE BK_PERSONAS ADD (
  CONSTRAINT PERSONAS_PK 
 PRIMARY KEY (ID_EMPRESA,ID_PERSONA));


ALTER TABLE BK_PERSONAS ADD (
  CONSTRAINT PER_EMP_FK 
 FOREIGN KEY (ID_EMPRESA) 
 REFERENCES BK_EMPRESAS (ID_EMPRESA));


CREATE TABLE BK_CUENTAS (
ID_EMPRESA VARCHAR2(100),
ID_CUENTA VARCHAR(200),
TIPO_CUENTA VARCHAR2(240),
NRO_CUENTA VARCHAR2(240),
DESCRIPCION1 VARCHAR2(240) NOT NULL,
DESCRIPCION2  VARCHAR2(240),
DESCRIPCION3 VARCHAR2(240)
);


ALTER TABLE BK_CUENTAS ADD (
  CONSTRAINT CUENTAS_PK 
 PRIMARY KEY (ID_EMPRESA,ID_CUENTA));


ALTER TABLE BK_CUENTAS ADD (
  CONSTRAINT CUE_EMP_FK 
 FOREIGN KEY (ID_EMPRESA) 
 REFERENCES BK_EMPRESAS (ID_EMPRESA));


CREATE TABLE BK_PERSONAS_CUENTAS (
ID_EMPRESA VARCHAR2(100),
ID_PERSONA VARCHAR2(200),
ID_CUENTA VARCHAR2(240)
);


ALTER TABLE BK_PERSONAS_CUENTAS ADD (
  CONSTRAINT USUCUE_PK 
 PRIMARY KEY (ID_PERSONA,ID_EMPRESA,ID_CUENTA));


ALTER TABLE BK_PERSONAS_CUENTAS ADD (
  CONSTRAINT PCUE_EMP_FK
  FOREIGN  key ( ID_EMPRESA) 
 REFERENCES BK_EMPRESAS (ID_eMPRESA));

ALTER TABLE BK_PERSONAS_CUENTAS ADD (
  CONSTRAINT PCUE_PER_FK
  FOREIGN  key ( ID_EMPRESA,ID_PERSONA) 
 REFERENCES BK_PERSONAS (ID_EMPRESA,ID_PERSONA));


CREATE TABLE BK_PARAMETROS
(
  ID_EMPRESA     VARCHAR2(100),
  CODIGO         VARCHAR2(240 BYTE)             NOT NULL,
  OBSERVACIONES  VARCHAR2(2000 BYTE),
  VALOR          VARCHAR2(4000 BYTE)
);
 

ALTER TABLE BK_PARAMETROS ADD (
  CONSTRAINT PARAM_PK PRIMARY KEY  
 (ID_EMPRESA,CODIGO)
 );
 

ALTER TABLE BK_PARAMETROS ADD (
  CONSTRAINT PARAM_EMP_FK
  FOREIGN  key ( ID_EMPRESA) 
 REFERENCES BK_EMPRESAS (ID_eMPRESA));
 
 
CREATE TABLE BK_CODIGOS_REFERENCIA
(
  ID_EMPRESA         VARCHAR2(100),
  RC_DOMINIO         VARCHAR2(240 BYTE)         NOT NULL,
  RC_VALOR           VARCHAR2(240 BYTE)         NOT NULL,
  RC_DESCRIPCION     VARCHAR2(240 BYTE),
  RC_ABREVIACION     VARCHAR2(240 BYTE),
  RC_CODIGO_EXTERNO  VARCHAR2(240 BYTE)
);



ALTER TABLE BK_CODIGOS_REFERENCIA 
ADD CONSTRAINT CORE_PK
PRIMARY KEY (ID_EMPRESA, RC_DOMINIO, RC_VALOR);


ALTER TABLE BK_CODIGOS_REFERENCIA ADD (
  CONSTRAINT REFE_EMP_FK
  FOREIGN  key ( ID_EMPRESA) 
 REFERENCES BK_EMPRESAS (ID_EMPRESA));

CREATE TABLE BK_DEUDAS
(
  ID_EMPRESA     VARCHAR2(100)                  NOT NULL,
  ID_COMPROBANTE VARCHAR2(240 BYTE)             NOT NULL,
  ID_CUENTA      VARCHAR2(200 BYTE),
  IMPORTE        NUMBER,
  FECHA_VTO      DATE,
  COD_CONCEPTO   VARCHAR2(4000 BYTE),
  DESC_CONCEPTO  VARCHAR2(4000 BYTE),
  DESCRIPCION    VARCHAR2(4000 BYTE),
  ESTADO         VARCHAR2(100)
);


   
ALTER TABLE BK_DEUDAS ADD CONSTRAINT
DEU_PK PRIMARY KEY ( ID_EMPRESA,ID_COMPROBANTE);


ALTER TABLE BK_DEUDAS ADD (
  CONSTRAINT DEU_CUE_FK
  FOREIGN  key ( ID_EMPRESA,ID_CUENTA) 
 REFERENCES BK_CUENTAS (ID_EMPRESA,ID_CUENTA));




CREATE TABLE BK_OPERACION_PAGO
(
  ID_OPERACION  INTEGER NOT NULL PRIMARY KEY,
  ID_EMPRESA    VARCHAR2(100) NOT NULL,
  FECHA         DATE,
  ID_OPERACION_OV  VARCHAR2(100 BYTE),
  IMPORTE       NUMBER,
  ESTADO        VARCHAR2(100)
);

ALTER TABLE BK_OPERACION_PAGO ADD (
  CONSTRAINT OP_EMP_FK
  FOREIGN  key ( ID_EMPRESA) 
 REFERENCES BK_EMPRESAS (ID_EMPRESA));


CREATE TABLE BK_OPERACION_DET_COMP
(
  ID_OPERACION   INTEGER                        NOT NULL,
  ID_EMPRESA     VARCHAR2(100)                  NOT NULL,
  ID_COMPROBANTE VARCHAR2(240 BYTE)             NOT NULL,
  ID_CUENTA      VARCHAR2(200 BYTE)             ,
  IMPORTE        NUMBER,
  FECHA_VTO      DATE,
  COD_CONCEPTO   VARCHAR2(4000 BYTE),
  DESC_CONCEPTO  VARCHAR2(4000 BYTE),
  DESCRIPCION    VARCHAR2(4000 BYTE)
);



ALTER TABLE BK_OPERACION_DET_COMP ADD CONSTRAINT
OP_COM_PK PRIMARY KEY ( ID_OPERACION,ID_COMPROBANTE,ID_EMPRESA);


ALTER TABLE BK_OPERACION_DET_COMP ADD (
  CONSTRAINT OPCP_OPER_FK
  FOREIGN  key ( ID_OPERACION) 
 REFERENCES BK_OPERACION_PAGO (ID_OPERACION));

ALTER TABLE BK_OPERACION_DET_COMP ADD (
  CONSTRAINT OPCP_DEU_FK
  FOREIGN  key ( ID_EMPRESA,ID_COMPROBANTE) 
 REFERENCES BK_DEUDAS (ID_EMPRESA,ID_COMPROBANTE));




 create sequence SEC_OPERACIONES_PAGO;
 
 
 