--
-- GE_TIPOS_DATO  (Table) 
--
CREATE TABLE GE_TIPOS_DATO
(
  TIPO_DATO    VARCHAR2(20 BYTE)                NOT NULL,
  DESCRIPCION  VARCHAR2(100 BYTE)               NOT NULL,
  TIPO         VARCHAR2(3 BYTE)                 NOT NULL,
  QUERY        VARCHAR2(4000 BYTE),
  ACTIVO       CHAR(1 BYTE)                     DEFAULT 'N'                   NOT NULL,
  MASCARA      VARCHAR2(100 BYTE)               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- RETIDA_PK  (Index) 
--
CREATE UNIQUE INDEX RETIDA_PK ON GE_TIPOS_DATO
(TIPO_DATO)
LOGGING
NOPARALLEL;



-- 
-- Non Foreign Key Constraints for Table GE_TIPOS_DATO 
-- 
ALTER TABLE GE_TIPOS_DATO ADD (
  CONSTRAINT AVCON_1503494086_ACTIV_000
 CHECK (ACTIVO IN ('N', 'S')));

ALTER TABLE GE_TIPOS_DATO ADD (
  CONSTRAINT RETIDA_PK
 PRIMARY KEY
 (TIPO_DATO));


--
-- GE_CONSULTAS  (Table) 
--
CREATE TABLE GE_CONSULTAS
(
  REPORTE      VARCHAR2(20 BYTE)                NOT NULL,
  NOMBRE       VARCHAR2(100 BYTE)               NOT NULL,
  DESCRIPCION  VARCHAR2(4000 BYTE),
  HTML         VARCHAR2(4000 BYTE),
  TIPO         NUMBER                           DEFAULT 1                     NOT NULL,
  QUERY        CLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- RECON_PK  (Index) 
--
CREATE UNIQUE INDEX RECON_PK ON GE_CONSULTAS
(REPORTE)
LOGGING
NOPARALLEL;


-- 
-- Non Foreign Key Constraints for Table GE_CONSULTAS 
-- 
ALTER TABLE GE_CONSULTAS ADD (
  CONSTRAINT RECON_PK
 PRIMARY KEY
 (REPORTE));


--
-- GE_REPORTE_PARAMETROS  (Table) 
--
CREATE TABLE GE_REPORTE_PARAMETROS
(
  PARAMETRO    VARCHAR2(100 BYTE)               NOT NULL,
  DESCRIPCION  VARCHAR2(100 BYTE),
  PROMPT       VARCHAR2(100 BYTE),
  ORDEN        NUMBER(3),
  REPORTE      VARCHAR2(20 BYTE)                NOT NULL,
  TIPO_DATO    VARCHAR2(20 BYTE)                NOT NULL,
  MULTIPLE     VARCHAR2(1 BYTE)                 DEFAULT 'N'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--
-- REREPA_RETIDA_FK_I  (Index) 
--
CREATE INDEX REREPA_RETIDA_FK_I ON GE_REPORTE_PARAMETROS
(TIPO_DATO)
LOGGING
NOPARALLEL;


--
-- REREPA_RECON_FK_I  (Index) 
--
CREATE INDEX REREPA_RECON_FK_I ON GE_REPORTE_PARAMETROS
(REPORTE)
LOGGING
NOPARALLEL;


--
-- REREPA_PK  (Index) 
--
CREATE UNIQUE INDEX REREPA_PK ON GE_REPORTE_PARAMETROS
(PARAMETRO, REPORTE)
LOGGING
NOPARALLEL;


-- 
-- Non Foreign Key Constraints for Table GE_REPORTE_PARAMETROS 
-- 
ALTER TABLE GE_REPORTE_PARAMETROS ADD (
  CONSTRAINT REREPA_PK
 PRIMARY KEY
 (PARAMETRO, REPORTE));


-- 
-- Foreign Key Constraints for Table GE_REPORTE_PARAMETROS 
-- 
ALTER TABLE GE_REPORTE_PARAMETROS ADD (
  CONSTRAINT REREPA_RETIDA_FK 
 FOREIGN KEY (TIPO_DATO) 
 REFERENCES GE_TIPOS_DATO (TIPO_DATO));


ALTER TABLE GE_REPORTE_PARAMETROS ADD (
  CONSTRAINT REREPA_CONSUL_FK 
 FOREIGN KEY (REPORTE) 
 REFERENCES GE_CONSULTAS (REPORTE));



