select ID_EMPRESA,NRO_LEGAJO,COUNT(1) from facturas_cliente where estado in ('CON','PAR')
GROUP BY ID_EMPRESA,NRO_LEGAJO
ORDER BY 3 DESC

SELECT * FROM CLIENTES --WHERE cuit=30999161304


select * from facturas_cliente a, clientes b, personas c 
where a.id_empresa=b.id_empresa
and a.nro_sucursal=b.nro_sucursal
and a.nro_legajo=b.nro_legajo 
and a.estado in ('CON','PAR')
and b.cuit=c.cuit




and a.id_empresa=1 and a.nro_legajo=159




/* Formatted on 2020/01/17 20:48 (Formatter Plus v4.8.8) */
select "cont_id" , count(1) from (
SELECT   "CLIENTES"."CUIT" AS "cont_id", "FACTURAS_CLIENTE"."ID_EMPRESA",
         "FACTURAS_CLIENTE"."NRO_SUCURSAL", "FACTURAS_CLIENTE"."ID_FACTURA",
         "CLIENTES"."CUIT", "CLIENTES"."NRO_CUENTA",
         "FACTURAS_CLIENTE"."SALDO_IMPAGO" AS "deu_capital",
         "PERSONAS"."NOMBRE" AS "cont_desc1", "PERSONAS"."NOMBRE",
         "FACTURAS_CLIENTE"."FECHA_VENCIMIENTO" AS "deu_vto",
         "FACTURAS_CLIENTE"."TIPO_FACTURA", "FACTURAS_CLIENTE"."NRO_FACTURA"
    FROM "FACTURAS_CLIENTE" INNER JOIN "CLIENTES"
         ON "FACTURAS_CLIENTE"."ID_EMPRESA" = "CLIENTES"."ID_EMPRESA"
       AND "FACTURAS_CLIENTE"."NRO_SUCURSAL" = "CLIENTES"."NRO_SUCURSAL"
       AND "FACTURAS_CLIENTE"."NRO_LEGAJO" = "CLIENTES"."NRO_LEGAJO"
         INNER JOIN "PERSONAS" ON "CLIENTES"."CUIT" = "PERSONAS"."CUIT"
   WHERE "FACTURAS_CLIENTE"."ESTADO" IN ('CON', 'PAR')
   --and tipo_Factura<>'Z'
   )
group by "cont_id" 
order by 2 desc

 ORDER BY "PERSONAS"."NOMBRE" ASC,
         "CLIENTES"."NRO_CUENTA" ASC,
         "FACTURAS_CLIENTE"."ID_FACTURA" ASC,
         "FACTURAS_CLIENTE"."FECHA_VENCIMIENTO" DESC
  
 
 
 
 SELECT "CLIENTES"."CUIT" AS "cont_id","FACTURAS_CLIENTE"."ID_EMPRESA","FACTURAS_CLIENTE"."NRO_SUCURSAL","FACTURAS_CLIENTE"."ID_FACTURA","CLIENTES"."CUIT","CLIENTES"."NRO_CUENTA","FACTURAS_CLIENTE"."SALDO_IMPAGO" AS "deu_capital","PERSONAS"."NOMBRE" AS "cont_desc1","PERSONAS"."NOMBRE","FACTURAS_CLIENTE"."FECHA_GENERACION" AS "deu_vto","FACTURAS_CLIENTE"."TIPO_FACTURA","FACTURAS_CLIENTE"."NRO_FACTURA" FROM "FACTURAS_CLIENTE" INNER JOIN "CLIENTES" ON "FACTURAS_CLIENTE"."ID_EMPRESA" = "CLIENTES"."ID_EMPRESA" AND "FACTURAS_CLIENTE"."NRO_SUCURSAL" = "CLIENTES"."NRO_SUCURSAL" AND "FACTURAS_CLIENTE"."NRO_LEGAJO" = "CLIENTES"."NRO_LEGAJO" INNER JOIN "PERSONAS" ON "CLIENTES"."CUIT" = "PERSONAS"."CUIT" WHERE "FACTURAS_CLIENTE"."ESTADO" IN ('CON', 'PAR') AND "CLIENTES"."CUIT" = '30714884537' AND "FACTURAS_CLIENTE"."FECHA_GENERACION" < SYSDATE+30 ORDER BY "PERSONAS"."NOMBRE" ASC,"CLIENTES"."NRO_CUENTA" ASC,"FACTURAS_CLIENTE"."ID_FACTURA" ASC,"FACTURAS_CLIENTE"."FECHA_GENERACION" DESC 
 
 
 
 select NOMBRE,CUIT,NRO_INGRESOS_BRUTOS, B.CALLE,B.NRO,B.PISO , C.DESCRIPCION  , C.CODIGO_POSTAL 
 from EMPRESAS A INNER JOIN CONFIGURACIONES_EMPRESA B ON A.ID_EMPRESA = B.ID_EMPRESA
                 INNER JOIN LOCALIDADES C ON B.ID_LOCALIDAD=C.ID_LOCALIDAD


 select A.CAE ,A.FECHA_emision,A.IVA_INSCRIPTO,A.IVA_NO_INSCRIPTO,A.MONTO_TOTAL,a.NRO_FACTURA,a.TIPO_FACTURA
 from FACTURAS_CLIENTE A INNER JOIN CLIENTES B ON A.ID_EMPRESA = B.ID_EMPRESA AND A.NRO_SUCURSAL=B.NRO_SUCURSAL AND A.NRO_LEGAJO=B.NRO_LEGAJO
 
 
 select c.porcentaje_iva,c.DESCRIPCION,b.cantidad,b.precio,b.monto_iva,b.importe from FACTURAS_CLIENTE A INNER JOIN DETALLES_FACTURA_CLIENTE B ON A.ID_EMPRESA = B.ID_EMPRESA AND A.ID_fACTURA=B.ID_FACTURA 
                                  INNER JOIN productos  C ON B.ID_EMPRESA = C.ID_EMPRESA AND B.cod_producto=C.cod_producto AND B.cod_tipo_producto=C.cod_tipo_producto

 
  
 ID_EMPRESA=1
 
 SELECT CUIT,NRO_INGRESOS_BRUTOS  FROM  CONFIGURACIONES_EMPRESA